//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCharacter
    {
        public int Number { get; set; }
        public string Id { get; set; }
        public string GameID1 { get; set; }
        public string GameID2 { get; set; }
        public string GameID3 { get; set; }
        public string GameID4 { get; set; }
        public string GameID5 { get; set; }
        public string GameIDC { get; set; }
    }
}
