//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddItemModify
    {
        public int Number { get; set; }
        public Nullable<byte> cType { get; set; }
        public Nullable<byte> IvenPos { get; set; }
        public Nullable<byte> bfLevel { get; set; }
        public Nullable<byte> bfOption1 { get; set; }
        public Nullable<byte> bfOption2 { get; set; }
        public Nullable<byte> bfOption3 { get; set; }
    }
}
