//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admit_Info
    {
        public int Number { get; set; }
        public string DemanderID { get; set; }
        public string AdmiterID { get; set; }
        public string SupervisorID { get; set; }
        public string DemanderMemo { get; set; }
        public string AdmiterMemo { get; set; }
        public string SupervisorMemo { get; set; }
        public string MoreInfo { get; set; }
        public string AccountID { get; set; }
        public string GameID { get; set; }
        public Nullable<short> ServerNumber { get; set; }
        public Nullable<int> LinkTableType { get; set; }
        public Nullable<short> AdmitInfo { get; set; }
        public Nullable<short> SupervisorAdmitInfo { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> AdmitDate { get; set; }
        public Nullable<System.DateTime> SupervisorAdmitDate { get; set; }
    }
}
