//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCKING
    {
        public int block_guid { get; set; }
        public int memb_guid { get; set; }
        public int serv_guid { get; set; }
        public string char_name { get; set; }
        public string take_code { get; set; }
        public string take_cont { get; set; }
        public string memb_cont { get; set; }
        public string appl_days { get; set; }
        public string rels_days { get; set; }
        public string ctl1_code { get; set; }
    }
}
