//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCKING_LOG
    {
        public System.DateTime appl_days { get; set; }
        public int admin_guid { get; set; }
        public int block_guid { get; set; }
        public string dist_code { get; set; }
        public string admin_name { get; set; }
    }
}
