//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public string AccountID { get; set; }
        public string Name { get; set; }
        public Nullable<short> cLevel { get; set; }
        public Nullable<int> LevelUpPoint { get; set; }
        public Nullable<byte> Class { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<short> Strength { get; set; }
        public Nullable<short> Dexterity { get; set; }
        public Nullable<short> Vitality { get; set; }
        public Nullable<short> Energy { get; set; }
        public byte[] Inventory { get; set; }
        public byte[] MagicList { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<float> Life { get; set; }
        public Nullable<float> MaxLife { get; set; }
        public Nullable<float> Mana { get; set; }
        public Nullable<float> MaxMana { get; set; }
        public Nullable<short> MapNumber { get; set; }
        public Nullable<short> MapPosX { get; set; }
        public Nullable<short> MapPosY { get; set; }
        public Nullable<byte> MapDir { get; set; }
        public Nullable<int> PkCount { get; set; }
        public Nullable<int> PkLevel { get; set; }
        public Nullable<int> PkTime { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public Nullable<byte> CtlCode { get; set; }
        public Nullable<byte> DbVersion { get; set; }
        public byte[] Quest { get; set; }
        public int resets { get; set; }
    }
}
