//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharInfoModify
    {
        public int Number { get; set; }
        public Nullable<int> cLevel { get; set; }
        public Nullable<int> LevelUpPoint { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<short> Strength { get; set; }
        public Nullable<short> Dexterity { get; set; }
        public Nullable<short> Vitality { get; set; }
        public Nullable<short> Energy { get; set; }
        public Nullable<float> Life { get; set; }
        public Nullable<float> MaxLife { get; set; }
        public Nullable<float> Mana { get; set; }
        public Nullable<float> MaxMana { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
    }
}
