//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURR_INFO
    {
        public int memb_guid { get; set; }
        public string chek_code { get; set; }
        public string ends_days { get; set; }
        public string used_time { get; set; }
        public string used___ip { get; set; }
        public string add___ip { get; set; }
        public string strt_days { get; set; }
        public string comp_guid { get; set; }
    }
}
