//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_INFO
    {
        public byte Server { get; set; }
        public byte Square { get; set; }
        public string AccountID { get; set; }
        public string CharacterName { get; set; }
        public byte Class { get; set; }
        public int Point { get; set; }
    }
}
