//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameServerInfo
    {
        public int Number { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> ZenCount { get; set; }
    }
}
