//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guild
    {
        public string G_Name { get; set; }
        public byte[] G_Mark { get; set; }
        public Nullable<int> G_Score { get; set; }
        public string G_Master { get; set; }
        public Nullable<int> G_Count { get; set; }
        public string G_Notice { get; set; }
        public int Number { get; set; }
    }
}
