//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANG_INFO
    {
        public int mang_guid { get; set; }
        public string mang___id { get; set; }
        public string mang__pwd { get; set; }
        public string mang_name { get; set; }
        public string mail_addr { get; set; }
        public string levl_name { get; set; }
        public string part_name { get; set; }
        public string auth_code { get; set; }
        public string appl_days { get; set; }
        public string ctl1_code { get; set; }
        public string Group_code { get; set; }
        public string dep_code { get; set; }
        public int perm { get; set; }
    }
}
