//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMB_STAT
    {
        public string memb___id { get; set; }
        public Nullable<byte> ConnectStat { get; set; }
        public string ServerName { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> ConnectTM { get; set; }
        public Nullable<System.DateTime> DisConnectTM { get; set; }
    }
}
