//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembInfoModify
    {
        public int Number { get; set; }
        public string memb___id { get; set; }
        public string memb__pwd { get; set; }
        public string memb_name { get; set; }
        public string sno__numb { get; set; }
        public string tel__numb { get; set; }
        public string phon_numb { get; set; }
        public string mail_addr { get; set; }
        public string fpas_ques { get; set; }
        public string fpas_answ { get; set; }
        public string bloc_code { get; set; }
    }
}
