//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMB__OUT
    {
        public int out__guid { get; set; }
        public int memb_guid { get; set; }
        public string sno__numb { get; set; }
        public string memb_name { get; set; }
        public Nullable<System.DateTime> appl_days { get; set; }
        public string ctl1_code { get; set; }
    }
}
