//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIDS_INFO
    {
        public int mids_guid { get; set; }
        public int memb_guid { get; set; }
        public string chek_code { get; set; }
        public string prev_info { get; set; }
        public string modi_info { get; set; }
        public string cont_text { get; set; }
        public string admin_name { get; set; }
        public string appl_days { get; set; }
    }
}
