//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MuOnlineEntities : DbContext
    {
        public MuOnlineEntities()
            : base("name=MuOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountCharacter> AccountCharacter { get; set; }
        public DbSet<Character> Character { get; set; }
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<MEMB_INFO> MEMB_INFO { get; set; }
        public DbSet<MEMB_STAT> MEMB_STAT { get; set; }
        public DbSet<VI_CURR_INFO> VI_CURR_INFO { get; set; }
        public DbSet<AddItemModify> AddItemModify { get; set; }
        public DbSet<Admit_Info> Admit_Info { get; set; }
        public DbSet<BLOCKING> BLOCKING { get; set; }
        public DbSet<BLOCKING_LOG> BLOCKING_LOG { get; set; }
        public DbSet<CharInfoModify> CharInfoModify { get; set; }
        public DbSet<CharInfoModifyOrigin> CharInfoModifyOrigin { get; set; }
        public DbSet<ConnBlockList> ConnBlockList { get; set; }
        public DbSet<CURR_INFO> CURR_INFO { get; set; }
        public DbSet<DelItemModify> DelItemModify { get; set; }
        public DbSet<DEPART_TBL> DEPART_TBL { get; set; }
        public DbSet<EVENT_INFO> EVENT_INFO { get; set; }
        public DbSet<FQNW_MODI> FQNW_MODI { get; set; }
        public DbSet<GameServerInfo> GameServerInfo { get; set; }
        public DbSet<Guild> Guild { get; set; }
        public DbSet<GuildMember> GuildMember { get; set; }
        public DbSet<LEAV_MEMB> LEAV_MEMB { get; set; }
        public DbSet<MANG_INFO> MANG_INFO { get; set; }
        public DbSet<MEMB__OUT> MEMB__OUT { get; set; }
        public DbSet<MEMB_DESC> MEMB_DESC { get; set; }
        public DbSet<MEMB_DETA> MEMB_DETA { get; set; }
        public DbSet<MEMB_NOTICE> MEMB_NOTICE { get; set; }
        public DbSet<MembInfoModify> MembInfoModify { get; set; }
        public DbSet<MembInfoModifyOrigin> MembInfoModifyOrigin { get; set; }
        public DbSet<MIDS_INFO> MIDS_INFO { get; set; }
        public DbSet<MngLog> MngLog { get; set; }
        public DbSet<MngModifyLog> MngModifyLog { get; set; }
        public DbSet<MUMNG_AUTH_SKILL> MUMNG_AUTH_SKILL { get; set; }
        public DbSet<MUMNG_MANG_INFO> MUMNG_MANG_INFO { get; set; }
        public DbSet<MUMNG_SKILL_INFO> MUMNG_SKILL_INFO { get; set; }
        public DbSet<OptionData> OptionData { get; set; }
        public DbSet<UUID_LOGINNAME_MAP> UUID_LOGINNAME_MAP { get; set; }
        public DbSet<VI_FQNW_INFO> VI_FQNW_INFO { get; set; }
        public DbSet<VI_LEAV_INFO> VI_LEAV_INFO { get; set; }
        public DbSet<VI_MIDS_INFO> VI_MIDS_INFO { get; set; }
        public DbSet<warehouse> warehouse { get; set; }
        public DbSet<vCharacterPreview> vCharacterPreview { get; set; }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int SP_POINT_ACCUMULATION(Nullable<byte> server, Nullable<byte> square, string accountID, string characterName, Nullable<byte> @class, Nullable<int> point)
        {
            var serverParameter = server.HasValue ?
                new ObjectParameter("Server", server) :
                new ObjectParameter("Server", typeof(byte));
    
            var squareParameter = square.HasValue ?
                new ObjectParameter("Square", square) :
                new ObjectParameter("Square", typeof(byte));
    
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var characterNameParameter = characterName != null ?
                new ObjectParameter("CharacterName", characterName) :
                new ObjectParameter("CharacterName", typeof(string));
    
            var classParameter = @class.HasValue ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(byte));
    
            var pointParameter = point.HasValue ?
                new ObjectParameter("Point", point) :
                new ObjectParameter("Point", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_POINT_ACCUMULATION", serverParameter, squareParameter, accountIDParameter, characterNameParameter, classParameter, pointParameter);
        }
    
        public virtual int WZ_CharInfoChange(string adminId, string mess, string action, string accId, string gameID, Nullable<int> gamenum, string unknow2, Nullable<int> cLevel1, Nullable<int> up1, Nullable<int> exp1, Nullable<int> st1, Nullable<int> dex1, Nullable<int> vi1, Nullable<int> en1, Nullable<int> mlift1, Nullable<int> dlift1, Nullable<int> mmagic1, Nullable<int> dmagic1, Nullable<int> cLevel2, Nullable<int> up2, Nullable<int> exp2, Nullable<int> st2, Nullable<int> dex2, Nullable<int> vi2, Nullable<int> en2, Nullable<int> mlift2, Nullable<int> dlift2, Nullable<int> mmagic2, Nullable<int> dmagic2)
        {
            var adminIdParameter = adminId != null ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(string));
    
            var messParameter = mess != null ?
                new ObjectParameter("mess", mess) :
                new ObjectParameter("mess", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var accIdParameter = accId != null ?
                new ObjectParameter("AccId", accId) :
                new ObjectParameter("AccId", typeof(string));
    
            var gameIDParameter = gameID != null ?
                new ObjectParameter("GameID", gameID) :
                new ObjectParameter("GameID", typeof(string));
    
            var gamenumParameter = gamenum.HasValue ?
                new ObjectParameter("gamenum", gamenum) :
                new ObjectParameter("gamenum", typeof(int));
    
            var unknow2Parameter = unknow2 != null ?
                new ObjectParameter("unknow2", unknow2) :
                new ObjectParameter("unknow2", typeof(string));
    
            var cLevel1Parameter = cLevel1.HasValue ?
                new ObjectParameter("cLevel1", cLevel1) :
                new ObjectParameter("cLevel1", typeof(int));
    
            var up1Parameter = up1.HasValue ?
                new ObjectParameter("Up1", up1) :
                new ObjectParameter("Up1", typeof(int));
    
            var exp1Parameter = exp1.HasValue ?
                new ObjectParameter("exp1", exp1) :
                new ObjectParameter("exp1", typeof(int));
    
            var st1Parameter = st1.HasValue ?
                new ObjectParameter("st1", st1) :
                new ObjectParameter("st1", typeof(int));
    
            var dex1Parameter = dex1.HasValue ?
                new ObjectParameter("dex1", dex1) :
                new ObjectParameter("dex1", typeof(int));
    
            var vi1Parameter = vi1.HasValue ?
                new ObjectParameter("vi1", vi1) :
                new ObjectParameter("vi1", typeof(int));
    
            var en1Parameter = en1.HasValue ?
                new ObjectParameter("en1", en1) :
                new ObjectParameter("en1", typeof(int));
    
            var mlift1Parameter = mlift1.HasValue ?
                new ObjectParameter("mlift1", mlift1) :
                new ObjectParameter("mlift1", typeof(int));
    
            var dlift1Parameter = dlift1.HasValue ?
                new ObjectParameter("dlift1", dlift1) :
                new ObjectParameter("dlift1", typeof(int));
    
            var mmagic1Parameter = mmagic1.HasValue ?
                new ObjectParameter("mmagic1", mmagic1) :
                new ObjectParameter("mmagic1", typeof(int));
    
            var dmagic1Parameter = dmagic1.HasValue ?
                new ObjectParameter("dmagic1", dmagic1) :
                new ObjectParameter("dmagic1", typeof(int));
    
            var cLevel2Parameter = cLevel2.HasValue ?
                new ObjectParameter("cLevel2", cLevel2) :
                new ObjectParameter("cLevel2", typeof(int));
    
            var up2Parameter = up2.HasValue ?
                new ObjectParameter("Up2", up2) :
                new ObjectParameter("Up2", typeof(int));
    
            var exp2Parameter = exp2.HasValue ?
                new ObjectParameter("exp2", exp2) :
                new ObjectParameter("exp2", typeof(int));
    
            var st2Parameter = st2.HasValue ?
                new ObjectParameter("st2", st2) :
                new ObjectParameter("st2", typeof(int));
    
            var dex2Parameter = dex2.HasValue ?
                new ObjectParameter("dex2", dex2) :
                new ObjectParameter("dex2", typeof(int));
    
            var vi2Parameter = vi2.HasValue ?
                new ObjectParameter("vi2", vi2) :
                new ObjectParameter("vi2", typeof(int));
    
            var en2Parameter = en2.HasValue ?
                new ObjectParameter("en2", en2) :
                new ObjectParameter("en2", typeof(int));
    
            var mlift2Parameter = mlift2.HasValue ?
                new ObjectParameter("mlift2", mlift2) :
                new ObjectParameter("mlift2", typeof(int));
    
            var dlift2Parameter = dlift2.HasValue ?
                new ObjectParameter("dlift2", dlift2) :
                new ObjectParameter("dlift2", typeof(int));
    
            var mmagic2Parameter = mmagic2.HasValue ?
                new ObjectParameter("mmagic2", mmagic2) :
                new ObjectParameter("mmagic2", typeof(int));
    
            var dmagic2Parameter = dmagic2.HasValue ?
                new ObjectParameter("dmagic2", dmagic2) :
                new ObjectParameter("dmagic2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_CharInfoChange", adminIdParameter, messParameter, actionParameter, accIdParameter, gameIDParameter, gamenumParameter, unknow2Parameter, cLevel1Parameter, up1Parameter, exp1Parameter, st1Parameter, dex1Parameter, vi1Parameter, en1Parameter, mlift1Parameter, dlift1Parameter, mmagic1Parameter, dmagic1Parameter, cLevel2Parameter, up2Parameter, exp2Parameter, st2Parameter, dex2Parameter, vi2Parameter, en2Parameter, mlift2Parameter, dlift2Parameter, mmagic2Parameter, dmagic2Parameter);
        }
    
        public virtual int WZ_CONNECT_MEMB(string uid, string server, string uip)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var serverParameter = server != null ?
                new ObjectParameter("server", server) :
                new ObjectParameter("server", typeof(string));
    
            var uipParameter = uip != null ?
                new ObjectParameter("uip", uip) :
                new ObjectParameter("uip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_CONNECT_MEMB", uidParameter, serverParameter, uipParameter);
        }
    
        public virtual int WZ_DISCONNECT_MEMB(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_DISCONNECT_MEMB", uidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WZ_GetItemSerial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WZ_GetItemSerial");
        }
    
        public virtual ObjectResult<Nullable<int>> WZ_GuildCreate(string guildName, string masterName)
        {
            var guildNameParameter = guildName != null ?
                new ObjectParameter("GuildName", guildName) :
                new ObjectParameter("GuildName", typeof(string));
    
            var masterNameParameter = masterName != null ?
                new ObjectParameter("MasterName", masterName) :
                new ObjectParameter("MasterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WZ_GuildCreate", guildNameParameter, masterNameParameter);
        }
    
        public virtual int WZ_SetGuildDelete(string guild)
        {
            var guildParameter = guild != null ?
                new ObjectParameter("guild", guild) :
                new ObjectParameter("guild", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_SetGuildDelete", guildParameter);
        }
    
        public virtual int WZ_WriteLog(string uid, string uip, Nullable<int> ud, string ust)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var uipParameter = uip != null ?
                new ObjectParameter("uip", uip) :
                new ObjectParameter("uip", typeof(string));
    
            var udParameter = ud.HasValue ?
                new ObjectParameter("ud", ud) :
                new ObjectParameter("ud", typeof(int));
    
            var ustParameter = ust != null ?
                new ObjectParameter("ust", ust) :
                new ObjectParameter("ust", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_WriteLog", uidParameter, uipParameter, udParameter, ustParameter);
        }
    
        public virtual int WZ_WriteModifyLog(string mngID, string accID, string gameID, Nullable<int> server, string ip, string type, string text)
        {
            var mngIDParameter = mngID != null ?
                new ObjectParameter("MngID", mngID) :
                new ObjectParameter("MngID", typeof(string));
    
            var accIDParameter = accID != null ?
                new ObjectParameter("AccID", accID) :
                new ObjectParameter("AccID", typeof(string));
    
            var gameIDParameter = gameID != null ?
                new ObjectParameter("GameID", gameID) :
                new ObjectParameter("GameID", typeof(string));
    
            var serverParameter = server.HasValue ?
                new ObjectParameter("Server", server) :
                new ObjectParameter("Server", typeof(int));
    
            var ipParameter = ip != null ?
                new ObjectParameter("ip", ip) :
                new ObjectParameter("ip", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WZ_WriteModifyLog", mngIDParameter, accIDParameter, gameIDParameter, serverParameter, ipParameter, typeParameter, textParameter);
        }
    }
}
