//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionData
    {
        public string Name { get; set; }
        public byte[] SkillKey { get; set; }
        public Nullable<byte> GameOption { get; set; }
        public Nullable<byte> Qkey { get; set; }
        public Nullable<byte> Wkey { get; set; }
        public Nullable<byte> Ekey { get; set; }
        public Nullable<byte> ChatWindow { get; set; }
    }
}
