//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_CURR_INFO
    {
        public string ends_days { get; set; }
        public string chek_code { get; set; }
        public Nullable<int> used_time { get; set; }
        public string memb___id { get; set; }
        public string memb_name { get; set; }
        public int memb_guid { get; set; }
        public string sno__numb { get; set; }
        public Nullable<int> Bill_Section { get; set; }
        public Nullable<int> Bill_Value { get; set; }
        public Nullable<int> Bill_Hour { get; set; }
        public Nullable<int> Surplus_Point { get; set; }
        public Nullable<System.DateTime> Surplus_Minute { get; set; }
        public Nullable<int> Increase_Days { get; set; }
    }
}
