//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_LEAV_INFO
    {
        public string ctl1_code { get; set; }
        public string appl_days { get; set; }
        public string cont_text { get; set; }
        public string ctrl_text { get; set; }
        public string appl_code { get; set; }
        public int leav_guid { get; set; }
        public string memb_name { get; set; }
        public int memb_guid { get; set; }
        public string memb_mail { get; set; }
        public string sno__numb { get; set; }
        public string dist_code { get; set; }
        public string prss_name { get; set; }
        public string memb___id { get; set; }
        public string tel__numb { get; set; }
    }
}
